# Generated by Django 5.2.1 on 2025-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_alter_feedback_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
    ]
