# Generated by Django 5.2.1 on 2025-07-01 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_alter_feedback_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='bad_words_used',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='contains_bad_words',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='emoji',
        ),
        migrations.AddField(
            model_name='feedback',
            name='harsh_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
