# Generated by Django 5.2.1 on 2025-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0004_rename_text_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
