# Generated by Django 5.2.1 on 2025-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0005_feedback_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='harsh_words',
            new_name='bad_words_used',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='contains_bad_words',
            field=models.BooleanField(default=False),
        ),
    ]
