# Generated by Django 5.2.1 on 2025-07-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0006_rename_harsh_words_feedback_bad_words_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='bad_words_used',
            new_name='harsh_words',
        ),
    ]
