# Generated by Django 5.2.1 on 2025-07-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0007_rename_bad_words_used_feedback_harsh_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='comment',
        ),
    ]
