# Generated by Django 5.2.1 on 2025-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0008_rename_text_feedback_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contains_bad_words',
        ),
    ]
