# Generated by Django 5.2.1 on 2025-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0009_remove_feedback_contains_bad_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='harsh_words',
        ),
        migrations.AddField(
            model_name='feedback',
            name='bad_words_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contains_bad_words',
            field=models.BooleanField(default=False),
        ),
    ]
